site_name: GenLM Eval
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: blue
      primary: white

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            members_order_submodules: source
            group_by_category: false
            show_protocols: true
  - section-index
  - mkdocs-jupyter:
      execute: false
      allow_errors: false
      highlight_extra_classes: "custom-css-classes"
      include_source: true

nav:
  - Home: index.md
  - API Reference: reference/
  - Cookbook:
    - Supported Domains:
      - Pattern Matching: cookbook/domains/pattern_matching.ipynb
      - Text to SQL (Spider): cookbook/domains/spider.ipynb
      - Molecular Synthesis: cookbook/domains/molecular_synthesis.ipynb
    - Custom Domains: cookbook/custom_domains.ipynb

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html

repo_url: https://github.com/genlm/genlm-eval
