[build-system]
requires = ["setuptools>=64.0", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "genlm-eval"
version = "0.1.0"
description = "Evaluation framework for models in the GenLM ecosystem"
authors = []
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "pydantic",
    "numpy",
    "pandas",
]

[project.optional-dependencies]
pattern_matching = [
    "genlm-control>=0.2.1",
    "regex",
]

spider = [
    "genlm-control>=0.2.1",
    "jsons",
    "lark",
    "rapidfuzz",
]

molecules = [
    "genlm-control>=0.2.1",
    "rdkit",
    "partialsmiles",
]

json_schema_bench = [
    "datasets>=4.0.0",
    "jsonschema"
]

goal_inference = [
    "genlm-control>=0.2.1",
    "datasets>=4.0.0",
    "polars",
    "planetarium @ git+https://github.com/BatsResearch/planetarium.git"
]

test = [
    "genlm-control>=0.2.1",
    "coverage",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
]

docs = [
    "mkdocs",
    "mkdocs-jupyter",
    "mkdocstrings[python]",
    "mkdocs-material",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-section-index",
]

[tool.setuptools.packages.find]
include = ["genlm", "genlm/eval"]
