name: Codebase tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run Tests
        run: |
          uv venv --python 3.11
          source .venv/bin/activate
          uv pip install -e .[test,spider,molecules,pattern_matching,json_schema_bench,goal_inference,ds1000,livecodebench]
          python -m nltk.downloader punkt_tab
          pytest tests --cov=genlm/eval --cov-report=json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          slug: genlm/genlm-eval
